---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
- name: Install necessary packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ additional_packages | default([]) }}"
  when: additional_packages is defined