---
argument_specs:
  main:
    short_description: Manage the installation of necessary packages
    options:
      additional_packages:
        description: The desired packages to install
        type: list
        elements: str
        default: []
